/**
 * Created by Administrator on 2017/6/29.
 */
export default {
  data(){
    return {
      overviewList:[
        {
          type:'总收支',
          icon:'icon-zongshouzhi',
          details:[
            {
              type:'总收入',
              value:99999,
              ratio:2,
            },
            {
              type:'总支出',
              value:99999,
              ratio:2,
            },
            {
              type:'总收支',
              value:99999,
              ratio:2,
            },
          ]
        },
        {
          type:'总盈亏',
          icon:'icon-zongyingkui',
          details:[
            {
              type:'总盈利',
              value:99999,
              ratio:2,
            },
            {
              type:'总亏损',
              value:99999,
              ratio:2,
            },
            {
              type:'总盈亏',
              value:99999,
              ratio:2,
            },
          ]
        },
        {
          type:'总进出',
          icon:'icon-zongjinchu',
          details:[
            {
              type:'总入金',
              value:99999,
              ratio:2,
            },
            {
              type:'总出金',
              value:99999,
              ratio:2,
            },
            {
              type:'总进出',
              value:99999,
              ratio:2,
            },
          ]
        },
        {
          type:'交易商',
          icon:'icon-jiaoyishang',
          details:[
            {
              type:'收入',
              value:99999,
              ratio:2,
            },
            {
              type:'支出',
              value:99999,
              ratio:2,
            },
          ]
        },
        {
          type:'交易量',
          icon:'icon-jiaoyiliang',
          details:[
            {
              type:'交易量',
              value:99999,
              ratio:2,
            },
          ]
        },
        {
          type:'保证金',
          icon:'icon-baozhengjin',
          details:[
            {
              type:'保证金',
              value:99999,
              ratio:2,
            },
          ]
        }
      ],
      warnList:[
        {
          time:'2016-10-10 10:10:10',
          state:'waring',
          mes:'综合类会员1下属交易商2支付失败，请检查'
        },
        {
          time:'2016-10-10 10:10:10',
          state:'waring',
          mes:'综合类会员1下属交易商2支付失败，请检查'
        },
        {
          time:'2016-10-10 10:10:10',
          state:'waring',
          mes:'综合类会员1下属交易商2支付失败，请检查'
        }
      ],
    }
  },
  created:function(){
  },
  methods:{
  }
}
